export enum ErrorCode {
    CONTAINER_NOT_FOUND = 'CONTAINER_NOT_FOUND',
    INVALID_CONTAINER = 'INVALID_CONTAINER',
    INVALID_GRID_CONFIG = 'INVALID_GRID_CONFIG',
    INVALID_GRID_AREAS = 'INVALID_GRID_AREAS',
    COMPUTE_FAILED = 'COMPUTE_FAILED',
}
